<?php
// 引用函数库，设置基础环境信息
include('function.php');
include('curl.php');

if(!file_exists("images/")) {
	mkdir("images/");
	echo "Please put your background image into the \"images\" folder";
	exit;
}

// 获取文件夹内的所有图片
$dir = scandir("images/");
foreach($dir as $file) {
	if($file !== "." && $file !== ".." && $file !== "") {
		$fileList[] = $file;
	}
}
if(count($fileList) == 0) {
	echo "Please put your background image into the \"images\" folder";
	exit;
}

// 随机选取图片
$fileName = $fileList[mt_rand(0, count($fileList) - 1)];

// 取用户信息，获取要写的文本
$ip = $_SERVER["REMOTE_ADDR"];
$longitude = $geoip["longitude"];
$latitude = $geoip["latitude"];
$timezone = $geoip["timezone"];
$font = "./msyh.ttf";
$date = new DateTime("now", new DateTimeZone($timezone) );
$datetext = $date->format('Y-m-d H:i:s');

// 在图片上面写字
$img = imagecreatefrompng("images/{$fileName}");
$clr = ImageColorAllocate($img, 240, 240, 240);
imagettftext($img, 20, 0, 10, 50, $clr, $font, 
    "Welcome friends comes from ({$longitude}, {$latitude})");
imagettftext($img, 20, 0, 10, 80, $clr, $font, 
    "Now is {$datetext} in {$timezone}");
imagettftext($img, 20, 0, 10, 110, $clr, $font, 
    "Your IP Address is {$ip}");
imagettftext($img, 20, 0, 10, 140, $clr, $font, 
    "You are using {$bro} on {$os}");
imagettftext($img, 10, 0, 10, 200, $clr, $font, 
    "Image generated by github.com/mnixry/ZIPSign");

header("Content-type: image/PNG");
ImagePNG($img);
ImageDestroy($img);
